config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/favourites', to: 'favourite#show'
  get '/stores', to: 'store#index'
  resources :books do
	  put :favourite, on: :member
	end
	resources :authors
	resources :store, only: [:show, :search]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  has_many :favourites
	has_many :users, :through => :favourites
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/store.rb
class Store < ApplicationRecord
	geocoded_by :full_address
	after_validation :geocode
	def full_address
		"#{address}, #{city}, #{postcode}, #{state}, #{country}"
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favourites
	has_many :books, :through => :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def index
		@authors = Author.all
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [:show, :favourite]

	def index
		@books = Book.all.order(rating: :desc)
	end

	def show
		@book.views = @book.views + 1
		@book.save
	end

	def favourite
    type = params[:type]
    if type == "favourite"
      current_user.favourite << @book
      redirect_to favourites_path, notice: 'You favourited #{@book.title}'

    elsif type == "unfavourite"
      current_user.favourites.delete(@book)
      redirect_to favourites_path, notice: 'Unfavourited #{@book.title}'

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

  private

  def set_book
  	@book = Book.find(params[:id])
  end
end

app/controllers/favourite_controller.rb
class FavouriteController < ApplicationController
  def show
  	@favourites = current_user.favourites
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
	def index
		@stores = Store.all

		if params[:currentaddress].present?
			@currentaddress = params[:currentaddress]
			@store = Store.near("#{@currentaddress}", 8_000_000 , order: 'distance').first
		end
	end

	def show
		@store = Store.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@user = User.order(sign_in_count: :desc).first
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/favourite_helper.rb
module FavouriteHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>

<br/>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Img</th>
      <th>Books</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.img %></td>
        <td>
        	<% author.books.each do |book| %>
        	<ul>
						<li><%= book.title %></li> 
					</ul>
					<% end %>
				</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/index.html.erb
<h1>Books</h1>

<br/>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Img</th>
      <th>Author</th>
      <th>Rating</th>
      <th>Views</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book %></td>
        <td><%= image_tag(book.img, size: "180x250", alt: "best book online, books cheap best book") %></td>
        <td><%= book.author.name %></td>
        <td>
        	<% book.rating.times do %>
						*
      		<% end %>
        </td>
        <td><%= book.views %></td>
        <td><%= link_to "favourite",   favourite_book_path(book, type: "favourite"), method: :put %> </td>
        <td>
          <%= link_to "unfavourite", favourite_book_path(book, type: "unfavourite"), method: :put %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<title>Amazon - <%= @book.title %></title>
<h1>Title: <%= @book.title %></h1>
<%= image_tag(@book.img, size: "180x250", alt: "best book online, books cheap best book") %>
<p>Author: <%= @book.author.name %></p>
<p>Rating: <%= @book.rating %></p>
<p>Views: <%= @book.views %></p>

app/views/favourite/show.html.erb
<h1>Favourites</h1>
<% @favourites.each do |favourite| %>
	<h2>Title: <%= favourite.book.title %></h2>
	<%= image_tag(favourite.book.img, size: "180x250", alt: "best book online, books cheap best book") %>
	<p>Author: <%= favourite.book.author.name %></p>
	<p>Rating: <%= favourite.book.rating %></p>
	<p>Views: <%= favourite.book.views %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon - books books books</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <%= link_to 'Home', root_path, :class => 'navbar-brand' %>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to("Books", books_path) %></li>
            <li><%= link_to("Authors", authors_path)%></li>
            <li><%= link_to("Stores", stores_path) %></li>
            <li><%= link_to("Favourites", favourites_path) %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to(current_user.email, edit_user_registration_path) %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to('Sign in', new_user_session_path) %></li>
              <li><%= link_to('Sign up', new_user_registration_path) %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/store/index.html.erb
<h1>Stores</h1>

<br/>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Street</th>
      <th>City</th>
      <th>Postcode</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.title, store %></td>
        <td><%= store.address %></td>
        <td><%= store.city %></td>
        <td><%= store.postcode %></td>
        <td><%= store.state %></td>
        <td><%= store.country %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>

<%= form_tag(stores_path, method: :get) do %>
  <%= label_tag(:currentaddress, "Current Address:") %>
  <%= text_field_tag(:currentaddress) %>
  <%= submit_tag("Search") %>
<% end %>
<p>eg. 120 Brunswick St, Fortitude Valley QLD 4006</p><br>

<% if @store.present? %>

<strong>Closest store to you:</strong>
    <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Street</th>
      <th>City</th>
      <th>Postcode</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= link_to @store.title, @store %></td>
        <td><%= @store.address %></td>
        <td><%= @store.city %></td>
        <td><%= @store.postcode %></td>
        <td><%= @store.state %></td>
        <td><%= @store.country %></td>
      </tr>
  </tbody>
</table>
<% end %>

app/views/store/show.html.erb
<h1><%= @store.title %></h1>
<p>Street: <%= @store.address %></p>
<p>Suburb: <%= @store.city %></p>
<p>Postcode: <%= @store.postcode %></p>
<p>State: <%= @store.state %></p>
<p>Country: <%= @store.country %></p>

<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/streetview?key=AIzaSyB2cgMhO1FdlgQR37SzzGhzAIRaK5fHaA0
    &location=<%= @store.latitude %>,<%= @store.longitude %>" allowfullscreen>
</iframe>